# -*- coding: utf-8 -*-
#
# Configuration file for the Sphinx documentation builder.
#
# This file does only contain a selection of the most common options. For a
# full list see the documentation:
# http://www.sphinx-doc.org/en/master/config

import os

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
# import os
# import sys
# sys.path.insert(0, os.path.abspath('.'))


# -- Project information -----------------------------------------------------

project = "Universal Robots ROS 2 Driver Documentation"
copyright = "2024, Universal Robots A/S"
author = "Universal Robots A/S"

# The short X.Y version (shown in the sidebar; per-distro label)
# The full version, including alpha/beta/rc tags
release = "0.1"


# -- General configuration ---------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    "sphinx.ext.githubpages",
    "sphinx.ext.todo",
    "sphinx_copybutton",
    "sphinx_rtd_theme",
    "sphinx_tabs.tabs",
]

# Add any paths that contain templates here, relative to this directory.
templates_path = ["_templates"]

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
source_suffix = '.rst'

# The master toctree document.
master_doc = "index"
numfig = True

# ROS 2 distribution for this HTML build: humble | jazzy | kilted | rolling
# Set by scripts/build_docs.sh (or export ROS_DISTRO=... before sphinx-build).
ros_distro = os.environ.get("ROS_DISTRO", "rolling").lower()

_distro_meta = {
    "humble": ("Humble", "Humble Hawksbill"),
    "jazzy": ("Jazzy", "Jazzy Jalisco"),
    "kilted": ("Kilted", "Kilted Kaiju"),
    "rolling": ("Rolling", "Rolling Ridley"),
}
if ros_distro not in _distro_meta:
    raise ValueError(
        f"Unknown ROS_DISTRO={ros_distro!r}; expected one of: {', '.join(sorted(_distro_meta))}"
    )
distro_title, distro_title_full = _distro_meta[ros_distro]
version = distro_title

# Branch of *this* documentation repo for "Edit on GitHub" links
repos_file_branch = os.environ.get("DOCUMENTATION_GIT_BRANCH", "main")

# Pairs (slug, label) for the floating version switcher (paths under _build/html/)
_DOCUMENTATION_VERSION_SLUGS = (
    ("humble", "Humble"),
    ("jazzy", "Jazzy"),
    ("kilted", "Kilted"),
    ("rolling", "Rolling"),
)

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = "en"

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = ["_build", "Thumbs.db", ".DS_Store",
                    "**/CHANGELOG.rst", "**/README.rst",
                    "**/.work", # act temp files
                    ".venv", # local virtualenv
                   ]

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = None


# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = "sphinx_rtd_theme"

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ["_static"]

# Custom sidebar templates, must be a dictionary that maps document names
# to template names.
#
# The default sidebars (for documents that don't match any pattern) are
# defined by theme itself.  Builtin themes are using these templates by
# default: ``['localtoc.html', 'relations.html', 'sourcelink.html',
# 'searchbox.html']``.
#
# html_sidebars = {}


# -- Options for HTMLHelp output ---------------------------------------------

# Output file base name for HTML help builder.
htmlhelp_basename = "ur_documentationdoc"


# -- Options for LaTeX output ------------------------------------------------

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    #
    # 'papersize': 'letterpaper',
    # The font size ('10pt', '11pt' or '12pt').
    #
    # 'pointsize': '10pt',
    # Additional stuff for the LaTeX preamble.
    #
    # 'preamble': '',
    # Latex figure (float) alignment
    #
    # 'figure_align': 'htbp',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
    (
        master_doc,
        "ur_ros2_driver_documentation.tex",
        "UR ROS 2 Driver Documentation",
        "Universal Robots A/S",
        "manual",
    ),
]


# -- Options for manual page output ------------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [(master_doc, "ur_ros2_driverdocumentation", "UR ROS 2 Driver Documentation", [author], 1)]


# -- Options for Texinfo output ----------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (
        master_doc,
        "ur_ros2_driver_documentation",
        "ur_documentation Documentation",
        author,
        "ur_documentation",
        "One line description of project.",
        "Miscellaneous",
    ),
]


# -- Options for Epub output -------------------------------------------------

# Bibliographic Dublin Core info.
epub_title = project

# The unique identifier of the text. This can be a ISBN number
# or the project homepage.
#
# epub_identifier = ''

# A unique identification for the text.
#
# epub_uid = ''

# A list of files that should not be packed into the epub file.
epub_exclude_files = ["search.html"]


# -- Extension configuration -------------------------------------------------
copybutton_exclude = '.linenos, .gp, .go'

# -- Options for todo extension ----------------------------------------------

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = True

html_context = {
    "display_github": True,
    "github_user": "UniversalRobots",
    "github_repo": "Universal_Robots_ROS_Documentation",
    "github_version": repos_file_branch + "/",
    "conf_py_path": "/",
    "source_suffix": source_suffix,
}

html_logo = "_static/images/ur_logo.svg"
html_favicon = "_static/images/icon.svg"
html_css_files = [
    'css/ur_theme.css',
]

github_url = "https://github.com/UniversalRobots/Universal_Robots_ROS_Documentation"


def _html_page_context(app, pagename, templatename, context, doctree):
    """Relative links to the same page under other distro output directories."""
    depth = 1 + pagename.count("/")
    prefix = "../" * depth
    context["versions"] = [
        (label, f"{prefix}{slug}/{pagename}.html")
        for slug, label in _DOCUMENTATION_VERSION_SLUGS
    ]
    context["current_version"] = distro_title


def setup(app):
    app.connect("html-page-context", _html_page_context)
    return {"parallel_read_safe": True, "parallel_write_safe": True}
